"""하위 호환: gemini_llm → ai_client 재노출."""

from modules.ai_client import (  # noqa: F401
    API_KEY_URL,
    CHAT_SYSTEM_PROMPT,
    DEFAULT_MODEL,
    DEFAULT_PROVIDER,
    GEMINI_HOME,
    MODEL_CHOICES,
    MODELS,
    PROVIDER_GEMINI,
    PROVIDER_LABELS,
    PROVIDERS,
    api_key_path,
    chat_llm,
    clear_api_key,
    default_model_for,
    ensure_guide_file,
    friendly_error,
    gemini_status,
    has_api_key,
    invoke_llm,
    load_api_key,
    load_provider,
    models_for,
    save_api_key,
    save_provider,
    setup_guide_markdown,
    setup_guide_plain,
    test_connection,
)
